vich_uploader:
    db_driver: orm
    mappings:
        user_pictures:
            uri_prefix: /images/userPictures
            upload_destination: '%kernel.project_dir%/public/images/userPictures'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

